# CircleCI config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/challenge-bypass-extension
    steps:
      - run: sudo apt update
      - run: sudo apt install default-jre build-essential
      - checkout
      - run: git submodule update --init
      - run: yarn install
      - run: yarn lint
      - run: yarn build:all
      - run: yarn test:all
